name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main      # 需要部署的分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Export environment variables
        run: |
        node scripts/exportEnv.js > env.output
        cat env.output >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install
        working-directory: ./test_pages_branch 

      - name: Build project
        run: npm run build
        working-directory: ./test_pages_branch

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./test_pages_branch/dist
          destination_dir: ${{ env.BASE_PATH }}